# -*- coding: utf-8 -*-
"""Proyecto herramientas de programación

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GJGWFfOz3G563-d0DCUszl0Htioznthz
"""

import requests
import pandas as pd
import matplotlib.pyplot as plt

class AnalizadorFinanciero:

    """Clase para descargar y analizar precios de acciones y tasas de interés."""

    def __init__(self, symbols, api_key):
        # Lista de símbolos de acciones y clave de API
        self.symbols = symbols
        self.api_key = api_key
        self.stocks_df = pd.DataFrame()
        self.rate_df = pd.DataFrame()

    def descargar_acciones(self):

        """Descarga los precios diarios de cierre de una lista de símbolos usando Alpha Vantage."""

        df_total = pd.DataFrame()
        for sym in self.symbols:
            # Construir la URL para cada símbolo
            url_stock = f"https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol={sym}&outputsize=compact&apikey={self.api_key}"
            r = requests.get(url_stock).json()
            if "Time Series (Daily)" in r:
                # Convertir los datos a DataFrame y limpiar
                df = pd.DataFrame(r["Time Series (Daily)"]).T
                df = df.rename(columns={"4. close": sym})
                df[sym] = pd.to_numeric(df[sym])
                df.index = pd.to_datetime(df.index)
                df = df[[sym]]
                if df_total.empty:
                    df_total = df
                else:
                    df_total = df_total.join(df, how="outer")
                print(f"✅ {sym} descargado correctamente")
            else:
                print(f"⚠️ Error al descargar {sym}: {r}")
        self.stocks_df = df_total

    def descargar_tasa_interes(self):

        """Descarga la tasa de interés de EE.UU. a 10 años (US10Y) desde Alpha Vantage."""

        # URL para la tasa de interés de 10 años
        url_rate = f"https://www.alphavantage.co/query?function=TREASURY_YIELD&interval=daily&maturity=10year&apikey={self.api_key}"
        r_rate = requests.get(url_rate).json()
        if "data" in r_rate:
            # Procesar los datos de la tasa
            rate_df = pd.DataFrame(r_rate["data"])
            rate_df["date"] = pd.to_datetime(rate_df["date"])
            rate_df = rate_df.set_index("date")
            rate_df = rate_df[["value"]].rename(columns={"value": "US10Y"})
            rate_df["US10Y"] = pd.to_numeric(rate_df["US10Y"], errors="coerce")
            print("✅ Tasa de interés US10Y descargada correctamente")
            self.rate_df = rate_df
        else:
            print(f"⚠️ Error al descargar tasa US10Y: {r_rate}")
            self.rate_df = pd.DataFrame()

    def unir_datos(self):

        """Une la tasa de interés al DataFrame de acciones."""

        # Si hay datos de tasa, los adjuntamos
        if not self.rate_df.empty:
            self.stocks_df = self.stocks_df.join(self.rate_df, how="left")

    def resumen_list_comprehensions(self):

        """Ejemplos de list comprehensions útiles para el análisis financiero."""

        maximos = [self.stocks_df[sym].max() for sym in self.symbols]

        fechas_maximos = [self.stocks_df[sym].idxmax() for sym in self.symbols]

        promedios = [self.stocks_df[sym].mean() for sym in self.symbols]

        resumen_maximos = [(sym, self.stocks_df[sym].max(), self.stocks_df[sym].idxmax()) for sym in self.symbols]
        return maximos, fechas_maximos, promedios, resumen_maximos

    def graficar(self):

        """Grafica las acciones y la tasa de interés si está disponible."""

        plt.figure(figsize=(12,6))
        # Graficar cada acción
        for sym in self.symbols:
            plt.plot(self.stocks_df.index, self.stocks_df[sym], label=sym)
        # Si hay datos de tasa, graficar en eje secundario
        if "US10Y" in self.stocks_df.columns:
            ax1 = plt.gca()
            ax2 = ax1.twinx()
            ax2.plot(self.stocks_df.index, self.stocks_df["US10Y"], color="black", linestyle="--", label="Tasa US10Y (eje der)")
            ax2.set_ylabel("Tasa de Interés 10Y (%)")
            ax2.legend(loc="upper right")
        plt.legend(loc="upper left")
        plt.title("Acciones Tecnológicas y Tasa de Interés 10Y (Alpha Vantage)")
        plt.xlabel("Fecha")
        plt.ylabel("Precio Cierre (USD)")
        plt.show()

ALPHA_KEY = "B3Y2HVYOC803PSXQ"
symbols = ["AAPL", "AMZN", "MSFT", "NVDA", "TSLA"]


analizador = AnalizadorFinanciero(symbols, ALPHA_KEY)
analizador.descargar_acciones()
analizador.descargar_tasa_interes()
analizador.unir_datos()
maximos, fechas_maximos, promedios, resumen_maximos = analizador.resumen_list_comprehensions()
analizador.graficar()